import React from 'react';
import { X, MapPin, ShieldCheck, ShieldAlert, Shield, FileText } from 'lucide-react';
import { formatCurrency } from '../data/mockData';
import { Candidate } from '../utils/genieEngine';

export const CandidateDetail: React.FC<{ candidate: Candidate; city: string; onClose: () => void }> = ({ candidate, city, onClose }) => {
  const riskIcon = candidate.risk === 'low' ? <ShieldCheck className="w-4 h-4 mr-2 text-green-600" /> : candidate.risk === 'medium' ? <Shield className="w-4 h-4 mr-2 text-amber-600" /> : <ShieldAlert className="w-4 h-4 mr-2 text-red-600" />;

  return (
    <div className="fixed inset-0 bg-black/50 z-50 flex justify-end">
      <div className="w-full max-w-2xl bg-white h-full shadow-2xl flex flex-col">
        <div className="px-6 py-4 border-b border-gray-100 flex justify-between items-center bg-[#F8F9FA]">
          <div>
            <h2 className="text-xl font-bold text-[#1A1D23]">{candidate.name}</h2>
            <div className="flex items-center text-sm text-gray-500 mt-1"><MapPin className="w-3 h-3 mr-1" /> {city}</div>
          </div>
          <button onClick={onClose}><X className="w-5 h-5" /></button>
        </div>
        <div className="p-6 space-y-6 overflow-y-auto">
          <div className="bg-[#F8F9FA] p-4 rounded-lg">
            <div className="flex justify-between"><span>Composite Score</span><strong>{candidate.score}</strong></div>
            <div className="flex justify-between"><span>Quote</span><strong>{formatCurrency(candidate.quote)}</strong></div>
            <div className="flex justify-between"><span>Benchmark Median</span><strong>{formatCurrency(candidate.benchmarkMedian)}</strong></div>
          </div>
          <div>
            <h3 className="text-sm font-semibold mb-2">Score Breakdown</h3>
            <ul className="text-sm text-gray-700 space-y-1">
              <li>Quality: {candidate.quality}</li>
              <li>Reliability: {candidate.reliability}</li>
              <li>Risk score: {candidate.riskScore}</li>
            </ul>
          </div>
          <div className="bg-gray-50 p-3 rounded-md border text-sm">
            <div className="flex items-center font-medium mb-2">{riskIcon} {candidate.risk.toUpperCase()} RISK</div>
            <div>Source: {candidate.source}</div>
            <div className="text-xs text-gray-500 mt-2 flex items-center"><FileText className="w-3 h-3 mr-1" /> Generated by GENIE-US scoring engine.</div>
          </div>
        </div>
      </div>
    </div>
  );
};
